repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        exclude: "cemalloc/externals/.*"
    -   id: end-of-file-fixer
        exclude: "cemalloc/externals/.*"
    -   id: trailing-whitespace
        exclude: "cemalloc/externals/.*"
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    -   id: clang-format
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args: ['-I', '.codespell_ignore']
        exclude: "externals/.*"
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
